version: "3.8"

services:
  table-parser:
    build: .
    container_name: medical-table-parser
    ports:
      - "8511:8511"
    volumes:
      # Основная папка проекта монтируется прямо в /app
      - ./app:/app
      # Временные и логовые папки
      - ./temp:/app/temp
      - ./logs:/app/logs
      - ./screenshots:/app/screenshots
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
